version: '3'

services:
  web:
    image: hylkevds/frost-http-oms-v3:latest
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - serviceRootUrl=http://localhost:8080/FROST-Server
      - queueLoggingInterval=1000
      - http_cors_enable=true
      - http_cors_allowed_origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true
      - plugins_coreModel_enable=false
      - plugins_actuation_enable=false
      - plugins_multiDatastream_enable=false
      - plugins_odata_enable=true
      - plugins_openApi_enable=true
      - FROST_LL_service=debug

  database:
    image: postgis/postgis:14-3.2-alpine
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - postgis_volume:/var/lib/postgresql/data

volumes:
    postgis_volume:
